'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  (Form1E)
        '''Generate Japanese Kana file for WinBES99 extracting text from Image file
        '''created by scanner device.
        '''Kana is a collection of Japanese Letter excludes Kanji.
        '''WinBES99 is a text translation tool into Braille.
        '''Windows app &quot;Windows Fax and Scan&quot; can be used to create image file. 
        '''
        '''Requirement：To extranct text from image file,
        '''      This app requires &quot;Microsoft Office Document Imaging&quot;(MODI) installed.
        '''      See (Note) bellow.
        '''
        '''Starting by Menu:&quot;File&quot; --&gt; &quot;Open Image file&quot;,
        '''&quot;Extract&quot; on Image [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form1E() As String
            Get
                Return ResourceManager.GetString("help_form1E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form1)
        '''スキャナーで読み取ったイメージファイルから漢字かな混じり文を読み取って
        '''WinBES99 のためのかな入力ファイルを作成するツールです
        '''イメージファイルは &quot;Windows Fax と スキャン&quot; で スキャナーからイメージファイルを得ることができます
        '''
        '''要件：画像からテキストを読み取る場合は
        '''      &quot;Microsoft Office Document Imaging&quot;(MODI) がインストールされている必要があります
        '''      下記 (注) 参照
        '''
        '''メニューの &quot;ファイル&quot; ー＞ &quot;イメージファイルを開く&quot; から始め
        '''イメージファイル画面で &quot;読み取り&quot;ーー＞
        '''テキストファイル画面で &quot;かな変換&quot;ーー＞
        '''で、この画面にかなテキストファイルが表示されます
        '''
        '''長い行は折り返し表示されます
        '''&quot;Enter&quot;キーで行が分割され、改行マーク(⏎)の
        '''削除で行が連結されます
        '''
        '''半角カタカナは
        '''イメージ読み取りファイルから &quot;かな変換&quot; したときはひらがなに変換されます。
        '''半角カタカナを手入力した場合は
        '''&quot;かな表示&quot;、&quot;カナ表示&quot; ボタンで ひらがな、カタ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form1U8() As String
            Get
                Return ResourceManager.GetString("help_form1U8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form2)
        '''イメージファイルが表示されています
        '''&quot;読み取り&quot; ボタンを押すと
        '''読み取り結果が別のテキストフォームに表示されます
        '''読み取りには多少時間がかかります
        '''
        '''2017/04/29
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form2() As String
            Get
                Return ResourceManager.GetString("help_form2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form2E)
        '''Displaying document image file
        '''By &quot;Extract&quot; button,
        '''Extracted text is shown to another Form.
        '''This action expends a little bit time.
        '''
        '''2017/04/29
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form2E() As String
            Get
                Return ResourceManager.GetString("help_form2E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form3)
        '''イメージファイル読み取りの結果です
        '''読み取りエラーを修正してください
        '''&quot;かな変換&quot; ボタンを押すとメイン画面に
        '''かなテキストファイルが表示されます(多少時間がかかります)
        '''
        '''空白は読み取られません
        '''改行は大きなブロックごとに設定されています
        '''長い行は折り返し表示されます
        '''&quot;Enter&quot;キーで行が分割され、改行マーク(⏎)の
        '''削除で行が連結されます
        '''
        '''マウス右ボタンからカット＆ペースト、検索と置換
        '''記号入力ができます
        '''検索と置換のショートカットはCtrl+F キーです
        '''次を検索のショートカットは F3(上へ検索：Shift+F3)です
        '''
        '''2017/04/29
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form3() As String
            Get
                Return ResourceManager.GetString("help_form3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form3E)
        '''Text of Extracted from Document Image file
        '''Adjust line position error in extraction.
        '''&quot;Kana&quot; button translate kanji to Kana 
        '''and show result to main form.
        '''It take a little bit times.
        '''
        '''Space is ignored.
        '''Text is aplit to multiple lines roughly by blocks.
        '''Logn line is show folded.
        '''User Enter key to split line,
        '''delete EndOfLine sign(⏎) to concatinate lines.
        '''
        '''Mouse Right Button click popup context menu
        '''to Cut and Paste, Find/Replace dialog and Symbol Input Dialog.
        '''
        '''Shortcut key:
        '''  Ctrl+F [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form3E() As String
            Get
                Return ResourceManager.GetString("help_form3E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form5)
        '''画面フォント/印刷フォント:
        '''  フォントを設定します
        '''  左側のボタンを押すとフォント設定ダイアログが開きます
        '''  但し、スタイルは 標準、太字、斜体のみ選択できます
        '''  印刷用フォントを特に設定しない場合は
        '''  印刷フォント＝画面フォントにチェックを入れてください
        '''
        '''かな/カナの大文字/小文字変換キー:
        '''  あ&lt;--&gt;ぁ、ア&lt;--&gt;ァ、ｱ&lt;--&gt;ｧ のように
        '''  大文字&lt;--&gt;小文字 変換に使用する機能キー F1〜F12 を指定
        '''  シフトキーを押した状態でこのキーを押すと次の変換をします
        '''    は&lt;--&gt;わ、へ&lt;--&gt;え、う&lt;--&gt;ー
        '''
        '''記号文字入力ダイアログキー:
        '''  記号文字入力用のダイアログを開く機能キーを設定
        '''  マウス右ボタンで開くコンテクスメニューの&quot;記号入力&quot;でも
        '''  記号入力ダイアログを開くことができます
        '''
        '''点訳作法を考慮:
        '''  イメージ読み取りファイルからかな変換ファイルを生成するときに
        '''  以下の処理を行います
        '''    ・漢字の開始前にスペースを入れる
        '''        WinBES99での分かち書きがやりやすくなる
        '''  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form5() As String
            Get
                Return ResourceManager.GetString("help_form5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form5E)
        '''Print Font/Screen Font:
        '''  Setup Font
        '''  Open FontDialog when IconButton pushed.
        '''  Choose Standard/Bold/Italic only for FontStyle.
        '''
        '''Japanese Small/Large Letter Trans. Key:
        '''  Set PFKey Number(F1&lt;--&gt;F12) for translation of Small and large Japanese Letter like as
        '''    あ&lt;--&gt;ぁ、ア&lt;--&gt;ァ、ｱ&lt;--&gt;ｧ.
        '''  By the key with Shift modifier kety,following translation will be done.
        '''    は&lt;--&gt;わ、へ&lt;--&gt;え、う&lt;--&gt;ー
        '''
        '''Open Symbol Character Input Dialog Key:
        '''  Set PFKey to open &quot;Symbol Character Input&quot; Dialog
        '''  The dialog [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form5E() As String
            Get
                Return ResourceManager.GetString("help_form5E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form6)
        '''記号入力ダイアログ
        '''  引用符、括弧など IME変換を介さずに入力する場合に使用します
        '''
        '''  読み取り画面とかな変換画面で共通です
        '''  両画面を開いているときは、画面スィッチの度に
        '''  記号入力ダイアログキー(省略値:F6)を押してください
        '''
        '''  行を選択して &quot;送る&quot; を押してください
        '''  上から１０個までは Ctrl+1～Ctrl+0 キーでも入力できます
        '''
        '''  追加は現在の選択行の前に挿入されます
        '''  規定に戻すボタンでは省略値に戻します
        '''******************************************************************************
        '''  特殊な点字文字列を設定したい場合は WinBES99 の設定ファイル、
        '''  WIN-BES インストールフォルダー(例えば C:\Program Files\WIN-BES あるいは
        '''  C:\Program Files (x86)\WIN-BES) の special.def の最後に追加します
        '''
        '''  既定の次の文字列は 
        '''
        '''    &quot;~ﾟ[&quot;  :  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form6() As String
            Get
                Return ResourceManager.GetString("help_form6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form6E)
        '''Symbol Input Dialog
        '''  Input Quotation, Parenthesis, ... not by IME.
        '''
        '''  One dialog for both ExtractedText and KanaText form.
        '''  When both Form is opened, use &quot;Open Symbol dialog&quot; key(Default:F6)
        '''  to switch Form to be received.
        '''
        '''  Push &quot;Send&quot; button after a line selected.
        '''  Ctrl+1～Ctrl+0 sends a string from top 10.
        '''
        '''  &quot;Add&quot; inserts line before currently selected line.
        '''  &quot;Default&quot; button restores default values.
        '''***************************************************************************** [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form6E() As String
            Get
                Return ResourceManager.GetString("help_form6E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form7)
        '''記号入力追加ダイアログ
        '''  記号入力の追加設定ができます
        '''  文字列には記号文字に限らず任意の文字列を設定できます
        '''  コメントの指定はなくてもかまいません
        '''  点字文字を設定する方法は、記号入力ダイアログのヘルプを
        '''  見てください
        '''
        '''2017/04/29
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form7() As String
            Get
                Return ResourceManager.GetString("help_form7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  (Form7E)
        '''Symbol Add Dialog
        '''  You can set any string.
        '''  Comment column may be null.
        '''  To set Braille string, see Help of Symbol Input dialog.
        '''
        '''2017/04/29
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property help_form7E() As String
            Get
                Return ResourceManager.GetString("help_form7E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Icon_i2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon_i2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property Icon_i2k1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon_i2k1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader n [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Resources_en_GB() As String
            Get
                Return ResourceManager.GetString("Resources_en_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  イメージ(*.bmp;*.png;*.gif;*.jpg;*.jpeg;*.tif;*.tiff)|*.bmp;*.png;*.gif;*.jpg;*.jpeg;*.tif;*.tiff|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FILTER_IMAGE() As String
            Get
                Return ResourceManager.GetString("STR_FILTER_IMAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  かな変換テキスト(*.txt;*.text)|*.txt;*.text|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FILTER_KANATEXT() As String
            Get
                Return ResourceManager.GetString("STR_FILTER_KANATEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  読み取りテキスト(*.i2t)|*.i2t|テキスト(*.txt;*.text)|*.txt;*.text|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FILTER_KANJITEXT() As String
            Get
                Return ResourceManager.GetString("STR_FILTER_KANJITEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイルを開いてください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FORM1_INITIAL_TEXT() As String
            Get
                Return ResourceManager.GetString("STR_FORM1_INITIAL_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  かなテキスト に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FORM1_TITLE_KANA_FILE() As String
            Get
                Return ResourceManager.GetString("STR_FORM1_TITLE_KANA_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  漢字テキスト に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_FORM1_TITLE_KANJI_FILE() As String
            Get
                Return ResourceManager.GetString("STR_FORM1_TITLE_KANJI_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイルの変更を破棄しますか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_DISCARD_UPDATE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_DISCARD_UPDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイルが見つかりません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''   ページが最後のページです に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_PRINT_PAGE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_PRINT_PAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイル入力エラー に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_READ() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_READ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイル出力エラー に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_ERR_WRITE() As String
            Get
                Return ResourceManager.GetString("STR_MSG_ERR_WRITE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  テキストを表示しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_INFO_SHOW_TEXT() As String
            Get
                Return ResourceManager.GetString("STR_MSG_INFO_SHOW_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  テキストが設定されていません に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_NO_TEXT() As String
            Get
                Return ResourceManager.GetString("STR_MSG_NO_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ファイルが存在します上書きしますか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_MSG_REP_EXISTING() As String
            Get
                Return ResourceManager.GetString("STR_MSG_REP_EXISTING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  |新しいファイル| に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_NEWFILE() As String
            Get
                Return ResourceManager.GetString("STR_NEWFILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  |新規作成| に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_NEWTEXT() As String
            Get
                Return ResourceManager.GetString("STR_NEWTEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  無題 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property STR_NEWTEXT_FILE() As String
            Get
                Return ResourceManager.GetString("STR_NEWTEXT_FILE", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
